site_name: Arbitrary Waveform Creator
docs_dir: docs
theme:
  name: material
  language: en

plugins:
  - pdf-export

nav:
  - Home: index.md
  - Feature description: concArbitraryWaveformCreator.md    
  - Usage:
      - Start feature: taskStartArbitraryWaveformCreator.md
      - Create custom waveforms: taskCreateCustomWaveform.md
      - Define waveform beahavior: taskDefineCustomWaveformBehavior.md