site_name: Arbitrary Waveform Creator
docs_dir: docs
theme:
  name: material
  language: en

plugins:
  - search
  - with-pdf:
      output_path: document.pdf

      # Cover
      cover_title: Arbitrary Waveform Creator
      cover_subtitle: User Manual
      author: aufweiss TECHNISCHE DOKUMENTATION

      # Layout
      cover: true
      back_cover: true
      toc_title: Table of contents
      toc_level: 3

      # Seitenlayout
      two_columns_level: 0 # Ab welcher Überschriftenebene zweispaltig (0 = aus)

      # CSS für PDF
      css: stylesheets/pdf-styles.css

      # Rendering-Optionen
      render_js: true
      headless_chrome_path: chromium

      # Debug
      debug_html: false
      show_anchors: false
      verbose: true

# CSS für HTML
extra-css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Feature description: concArbitraryWaveformCreator.md    
  - Usage:
      - Start feature: taskStartArbitraryWaveformCreator.md
      - Create custom waveforms: taskCreateCustomWaveform.md
      - Define waveform beahavior: taskDefineCustomWaveformBehavior.md