site_name: Arbitrary Waveform Creator
docs_dir: docs
theme:
  name: material
  language: en

plugins:
  - search
  - pdf-export:
      combined: true
      combined_output_path: document.pdf
      media_type: print

extra-css:
  - stylesheets/pdfStyles.css

nav:
  - Home: index.md
  - Feature description: concArbitraryWaveformCreator.md    
  - Usage:
      - Start feature: taskStartArbitraryWaveformCreator.md
      - Create custom waveforms: taskCreateCustomWaveform.md
      - Define waveform beahavior: taskDefineCustomWaveformBehavior.md